### PR TITLE
Added test for Issue #682 and fixed.

### PR DESCRIPTION
**Pull request by jimmccusker**
Fixed issue #682.

### CODE REVIEW

**Comment by jimmccusker** [comment]
@joernhees, can I get some help from someone who knows python 3 better than I on these failures?

**Comment by jimmccusker** [comment]
The current error (in Py3) seems to expect IsomorphicGraph to be hashable:

```
...
  File "/home/travis/build/RDFLib/rdflib/rdflib/plugins/memory.py", line 254, in add
    self.__all_contexts.add(context)
TypeError: unhashable type: 'IsomorphicGraph'
```

**Comment by joernhees** [comment]
:-/ sad, i thought maybe just removing the py2 print statements already fixes it...

**Comment by joernhees** [comment]
aaaahaaa:

https://docs.python.org/3/reference/datamodel.html#object.__hash__
> ```A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking isinstance(obj, collections.Hashable).```

**Comment by joernhees** [comment]
@jimmccusker tests pass, but i'm not entirely sure f72b51a is the way to go... the store uses the hash as context (quads), so changing it as new triples are added is bad bad bad... however, hashing the full `IsomorphicGraph` should probably have something to do with its content?!? luckily we also have an `IsomorphicGraph.internal_hash` 🙄

**Comment by jimmccusker** [comment]
Right, that's the thing. __hash__ is supposed to be invariant. What does `set` do? It's hashable, but variant. Since RDF graphs are supposed to be sets of triples (or quads), maybe we can look there for guidance.

**Comment by gromgull** [comment]
Python sets are NOT hashable, precisely because they are mutable. That's
why there is "FrozenSet", this thing has to copy all the triples into a new
object that is unchangable. OR make a "FrozenGraph" subclass, that does not
allow writes, and hopes the underlying store is not changed during the
operation of checking isomorphism.




-- 
http://gromgull.net

**Comment by jimmccusker** [comment]
Then that argues that Graphs shouldn't be hashable either. For some reason, there seems to be a use case in Python 3 where graphs are expected to be hashable, but not in Python 2.7.

**Comment by joernhees** [comment]
hmm, not sure we're not getting hung up here on the alternative fact that IOMemory internally hashes the graph's identifier to transform triples into quads... i'm leaning toward hitting that the merge button and be done with this for now, but maybe we should add a cleanup issue to remove the `__hash__` from all mutable things and make IOMemory explicitly hash the identifier?

**Pull request merged**
