### PR TITLE
pre-commit and pre-commit-ci

### PR DESCRIPTION
**Pull request by aucampia**
Add pre-commit and pre-commit-ci with the following hooks:

- black for formatting code.

For more info see `docs/developers.rst`.

### CODE REVIEW

**Comment by aucampia** [comment]
@eggplants Please have a look if you have a moment and let me know if you have any feedback.

**Comment by aucampia** [comment]
For a demo see: https://github.com/aucampia/rdflib/pull/33/

I have enabled pre-commit CI now, but until this is merged it will always fail, it can be easily disabled from here: https://pre-commit.ci/

If we are in agreement on the settings there are the following options to actually run the hooks on the codebase:

1. We merge it and then wait for the weekly pre-commit CI auto fix - this happens 18:00 UTC Monday
2. We merge it and then make a emptyish PR and run `pre-commit.ci autofix` on it

Once this is done things will be fairly clean going forward, and each contributor can then either run `pre-commit run` by themselves or they/us can run `pre-commit.ci autofix` on their PR branches.

**Comment by aucampia** [comment]
Pycln is fairly conservative on what it cleans, it does actually ends up leaving a bunch of unsued imports, but only because they have side effects, for more info see: https://hadialqattan.github.io/pycln/#/?id=side-effects

**Comment by aucampia** [comment]
I will disable pre-commit.ci until this is merged. Can be controlled using github IAM at https://results.pre-commit.ci/ for future reference.

**Comment by aucampia** [comment]
Rebased to master branch.

I messed up the old demo, new one here: https://github.com/aucampia/rdflib/pull/35

**Comment by aucampia** [comment]
Will split the tox changes off this also as those will actually make development quite a bit easier.

**Comment by aucampia** [comment]
Given some feedback on other issues I'm going to scale this back to only run black to begin with, we can add other things afterwards.

**Comment by aucampia** [comment]
tox changes split into #1691

**Comment by aucampia** [comment]
Scaled this down to only do black.

**Review by nicholascar — APPROVED** [review]

**Comment by aucampia** [comment]
I changed the hook slightly to work with the version spec in black config, for more info see https://github.com/psf/black/issues/2493.

Demo updated and re-run: https://github.com/aucampia/rdflib/pull/35

Will merge next week sometime.

**Pull request merged**
