### PR TITLE
fix: DefinedNamespace: fixed handling of control attributes.

### PR DESCRIPTION
**Pull request by aucampia**
# Summary of changes

This patch changes `DefinedNamespace` to always raise `AttributeError` for
the name `_NS` and other "control attributes" from `__getattr__`, and to
also not consider them as part of the `__dir__`.

Without doign this `inspect.signature` recurses
infinitely when inspecting `rdflib.namespace.DefinedNamespace` and `dir`
results in an `AttributeError`.

One situation in which this occurs is when sphinx autodoc is generating
documentation from type hints:

```
WARNING: error while formatting signature for rdflib.namespace.DefinedNamespace: Handler <function record_typehints at 0x7fbf2696dd40> for event 'autodoc-process-signature' threw an exception (exception: maximum recursion depth exceeded while calling a Python object)
```

Also:
- Changed `DefinedNamespace.__repr__` to use repr for formatting
  the URI string instead of quoting by hand. This probably has no real effect,
  as the namespace shoudl not have a double or single quote in it, but
  it is still correct to use repr.

The main reason for this patch is to eliminate a warning for sphinx
which is blocking the build since `sphinx.fail_on_warning` was enabled.

There is also two cases in `DefinedNamespaceMeta` where an undefined
method is being called, these were causing type errors before, but I
added notes now to indicate they are real bugs, because if they are
reached they just result in `AttributeError` exceptions. This should be
fixed sometime, not sure what the reasoning behind it was.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.
- [x] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
This, together with https://github.com/RDFLib/rdflib/pull/1823, is needed to make docs build pass on master.

**Comment by aucampia** [comment]
Stack trace sample:

```
Traceback (most recent call last):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/.venv/lib64/python3.9/site-packages/sphinx/ext/autodoc/typehints.py", line 30, in record_typehints
    sig = inspect.signature(obj, type_aliases=app.config.autodoc_type_aliases)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/.venv/lib64/python3.9/site-packages/sphinx/util/inspect.py", line 637, in signature
    signature = inspect.signature(subject, follow_wrapped=follow_wrapped)
  File "/usr/lib64/python3.9/inspect.py", line 3113, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib64/python3.9/inspect.py", line 2862, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/lib64/python3.9/inspect.py", line 2295, in _signature_from_callable
    partialmethod = obj._partialmethod
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 235, in __contains__
    if item_str.startswith(str(cls._NS)):
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 219, in __getattr__
    return cls.__getitem__(name)
  File "/home/iwana/sw/d/github.com/iafork/rdflib.cleanish/rdflib/namespace/__init__.py", line 208, in __getitem__
    if (cls._warn or cls._fail) and name not in cls:
```

**Comment by aucampia** [comment]
I will actually add one more test to verify that `inspect.signature` on the namespace returns.

**Comment by aucampia** [comment]
I think there are deeper issues here, adding more tests.

**Comment by aucampia** [comment]
Okay, this fix is slightly wrong, reworking it.

**Comment by aucampia** [comment]
Okay it seems `DefinedNamespace` is severely broken, most of the super() stuff just will never run :/

**Comment by aucampia** [comment]
The remaining warning from sphinx is fixed in https://github.com/RDFLib/rdflib/pull/1823.

**Review by gjhiggins — APPROVED** [review]
Trickier than it looked at first.

**Comment by aucampia** [comment]
> Trickier than it looked at first.

Yes, also went down a couple of dead ends :sweat_smile: and fixed a couple of none bugs first  - thanks for the review.

**Comment by aucampia** [comment]
I will merge this tomorrow morning (CET) if there is no further feedback as this is blocking docs build and preview.

**Pull request merged**
