### PR TITLE
Issue 2378 goal: Get CI to pass without ALLOW_UNICODE on doctests

### LINKED ISSUE #2378: Is the pytest+doctest configuration ALLOW_UNICODE worth keeping?
I was looking through doctests, tried modifying one, fed the modified file into `python3 -m doctest`, and got many more errors than I was expecting.  Here's the excerpted shell transcript:

```
$ python3 -m doctest rdflib/term.py
[SNIP]
**********************************************************************
File "/tmp/rdflib/rdflib/term.py", line 702, in term.Literal.normalize
Failed example:
    Literal("a", datatype=XSD.integer, normalize=False)
Expected:
    rdflib.term.Literal(u'a', datatype=rdflib.term.URIRef(u'http://www.w3.org/2001/XMLSchema#integer'))
Got:
    rdflib.term.Literal('a', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer'))
**********************************************************************
9 items had failures:
   2 of  21 in term.Literal
   3 of   4 in term.Literal.__abs__
   2 of  10 in term.Literal.__add__
   3 of   4 in term.Literal.__invert__
   4 of   5 in term.Literal.__neg__
   4 of   5 in term.Literal.__pos__
  11 of  12 in term.Literal._literal_n3
  11 of  13 in term.Literal.n3
   2 of   3 in term.Literal.normalize
***Test Failed*** 42 failures.
```

The issue is that the docstrings' code snippets contain the Python 2 style of unicode string spelling, `u"some string"`.  This hasn't been flagged as a test failure because (and here I'm guessing) it seems the docstrings are tested with `pytest`, and `pytest` is [configured today](https://github.com/RDFLib/rdflib/blob/cbd61510ec581aee262bc2bb8ad95d94f7784842/pyproject.toml#L161) to use `ALLOW_UNICODE` to bypass this issue.

As part of moving on from Python 2, should `ALLOW_UNICODE` be removed, and the doc strings' tests updated?

FWIW, my experience note: 41 of the 42 issues in `rdflib/term.py` were mechanically addressable by just replacing `u'` with `'`.  However, the last issue that `python3 -m doctest` showed appeared to be a behavior change in the `<` operator for `Literal`s, and it's not clear to me whether the behavior change was something else that "Python 2 mode" was letting slip by.

I don't know how much work this would be.

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This PR sets the goal state for #2378:  Pass CI with a Python2 testing allowance for docstring tests removed.

This PR will be failing CI for a while.  My intent is to file separate PRs to `main` and keep catching this PR up until it eventually passes.  I'm aware of at least one patch that will be straightforward, one not so obvious, and am unsure how much further work would be needed.

Fixes #2378

# Summary of changes

This PR's sole contribution is expected to be removing `ALLOW_UNICODE` from `pyproject.toml`.  The rest is expected to be brought in via merging other PRs that lessen the tally of CI failures in this PR.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.  *(N/A)*
- [ ] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [x] Updated relevant documentation to avoid inaccuracies.  *(N/A)*
  - [x] Considered adding additional documentation.  *(N/A)*
  - [x] Considered adding an example in `./examples` for new features.  *(N/A)*
  - [ ] Considered updating our changelog (`CHANGELOG.md`).
- [ ] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Oh wait, I forgot part of my motivation for carving out other PRs:  I have smacked into at leas one issue that will require slightly harder work (handling an inequality operator in `Literal` vs. `URIRef`), so I wanted to do the less-thinking-required efforts in other PRs, and focused fixes in other PRs.

**Comment by aucampia** [comment]
> @aucampia sounds fine to me. Should #2384 be merged into `main` in the meanwhile, or should I just merge it into this branch and close that PR?

I will check it shortly, I think so though.

**Comment by aucampia** [comment]
> > @aucampia sounds fine to me. Should #2384 be merged into `main` in the meanwhile, or should I just merge it into this branch and close that PR?
> 
> I will check it shortly, I think so though.

Approved and merged. Apologies for taking so long to get to it, for small PRs like <https://github.com/RDFLib/rdflib/pull/2384> you should consider asking on [Gitter/Matrix](https://matrix.to/#/#RDFLib_rdflib:gitter.im). I try to process PRs in order, and sometimes I don't even look at new PRs before older ones are processed, if I knew it was so small I would have processed it sooner.

**Comment by aucampia** [comment]
PRs to V6 is closed until further notice. See this for more details:
- https://github.com/RDFLib/rdflib/discussions/2395

**Comment by aucampia** [comment]
> PRs to V6 is closed until further notice. See this for more details:
> 
> * [RDFLib V6 and V7 #2395](https://github.com/RDFLib/rdflib/discussions/2395)

We will be open for PRs again once this is resolved:

- https://github.com/RDFLib/rdflib/pull/2402

**Pull request merged**
