### PR TITLE
no relative import in when run as a script

### PR DESCRIPTION
**Pull request by cliffxuan**
original throws an exception
```
Traceback (most recent call last):
  File "plugins/sparql/algebra.py", line 787, in <module>
    from . import parser
ValueError: Attempted relative import in non-package
```

### CODE REVIEW

**Comment by joernhees** [comment]
could you provide a minimal example of what you're trying to do?

**Comment by cliffxuan** [comment]
just to run the script does not work currently because of the relative import 

```
➜  rdflib (master) python plugins/sparql/algebra.py "select * where {?s ?p ?o}"
```

**Comment by joernhees** [comment]
well, you can actually run it like this (this is a standard relative imports & path issue):
```
python -m plugins.sparql.algebra "select * where {?s ?p ?o}"
```

I agree that we could improve the usability of that as in 9d1318c .

5a895ff seems to be unrelated to me.

**Comment by joernhees** [comment]
@cliffxuan ok, i pulled 9d1318c into master, i'm closing this in case you want to re-open a pull request for 5a895ff

**Pull request closed without merging**
