### PR TITLE
Fix prov ns

### LINKED ISSUE #1308: Potentially missing terms in PROV namespace
Currently there are some terms defined in http://www.w3.org/ns/prov.ttl that are not in `rdflib.namespace.PROV`.

The only missing terms that match `[] rdfs:isDefinedBy <http://www.w3.org/ns/prov-o#> .` are ` [] rdf:type owl:AnnotationProperty .`, but `rdflib.namespace.PROV` already contains some terms which are annotation properties such as `wasRevisionOf` and `specializationOf`, however these terms are also object properties, so I guess there is some argument to be made the extra properties should not be in `rdflib.namespace.PROV`, however at the very least the inclusion criteria for `rdflib.namespace.PROV` should be clarified and documented in it's docstring.

I made a test to check it which can be found here: https://gitlab.com/aucampia/contrib/rdflib/-/blob/master/tests/test_namespace.py#L17

Output of the test is below, first element in tuples are the term URI, second is the ontology it was defined in.
```
$ FAILTESTS=1 poetry run nosetests -c nose.cfg tests.test_namespace:Namespace.test_prov
test_prov (tests.test_namespace.Namespace) ... FAIL

======================================================================
FAIL: test_prov (tests.test_namespace.Namespace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/iwana/syncthing/sw-wpw/d/gitlab.com/aucampia/contrib/rdflib/tests/test_namespace.py", line 71, in test_prov
    self.assertEqual(stated_term_set, defined_term_set)
AssertionError: Items in the first set but not the second:
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Contribute'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedDerivationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedAssociationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#ServiceDescription'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedUsingActivity'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#sharesDefinitionWith'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#definition'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#has_query_service'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Creator'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Removal'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasAssociateFor'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#unqualifiedForm'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#editorialNote'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#has_anchor'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasPrimarySourceOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Copyright'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedQuotationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#hadDictionaryMember'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedDelegationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasActivityOfInfluence'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#KeyEntityPair'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedSourceOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Insertion'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#DirectQueryService'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#EmptyDictionary'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#started'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Accept'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#order'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#asInBundle'), rdflib.term.URIRef('http://www.w3.org/ns/prov-links#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Dictionary'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasUsedInDerivation'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#todo'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedForm'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#RightsAssignment'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#category'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedInfluenceOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedInvalidationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#editorsDefinition'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Publisher'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#generalizationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasPlanOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#entityOfInfluence'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#RightsHolder'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedInsertion'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#ended'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#revisedEntity'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#derivedByInsertionFrom'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#describesService'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#locationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#pairEntity'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedEndOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#provenanceUriTemplate'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedAttributionOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#mentionOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-links#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#aq'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Publish'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#agentOfInfluence'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Contributor'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#generatedAsDerivation'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedCommunicationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#has_provenance'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#insertedKeyEntityPair'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#hadDelegate'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#informed'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#removedKey'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#component'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#hadDerivation'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasRoleIn'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#quotedAs'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedGenerationOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#derivedByRemovalFrom'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#n'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#constraints'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Create'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#dm'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#contributed'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#pingback'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#activityOfInfluence'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#pairKey'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasUsedBy'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedRemoval'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#qualifiedStartOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#hadInfluence'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#inverse'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Submit'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#wasMemberOf'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#dictionary'), rdflib.term.URIRef('http://www.w3.org/ns/prov#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#hadRevision'), rdflib.term.URIRef('http://www.w3.org/ns/prov-o-inverses#'))
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Replace'), None)
(rdflib.term.URIRef('http://www.w3.org/ns/prov#Modify'), None)

----------------------------------------------------------------------
Ran 1 test in 1.901s

FAILED (failures=1)
```

### PR DESCRIPTION
**Pull request by nicholascar**
Fixes #1308

## Proposed Changes

  - added missing terms
  - sorted all terms

@aucampia please review since you motivated this fix. Just want you to make sure I got it right.

### CODE REVIEW

**Comment by nicholascar** [comment]
This PR is failing tests with the "Cannot assign requested address" error so it the reviews are OK, I'll merge it (i.e. don't take the tests seriously).

**Review by aucampia — APPROVED** [review]
Looks good to me.

I ran a check with: [Namespace.test_prov](https://gitlab.com/aucampia/contrib/rdflib/-/blob/master/tests/test_namespace.py#L13) and it passes, also check sorting.

With this change `rdflib.namespace.PROV` will contain all terms matching `[] rdfs:isDefinedBy <http://www.w3.org/ns/prov-o#>` from `http://www.w3.org/ns/prov.ttl`.

**Comment by aucampia** [comment]
For reference the exact test I ran against it:

```python
    def test_prov(self) -> None:
        graph = Graph()
        graph.parse(source=(SCRIPT_PATH.parent / "data" / "prov.ttl"), format="turtle")

        qres = graph.query(
            r"""
            PREFIX owl: <http://www.w3.org/2002/07/owl#>
            SELECT DISTINCT ?term ?ontology WHERE {
                ?term ?p [].
                # MINUS { ?term rdf:type owl:AnnotationProperty }
                FILTER isIRI(?term).
                FILTER strStarts(str(?term), "http://www.w3.org/ns/prov#").
                FILTER (str(?term) != "http://www.w3.org/ns/prov#")
                OPTIONAL { ?term rdfs:isDefinedBy ?ontology }
            }
            """
        )
        owl_terms = {}
        for row in qres:
            owl_terms[row["term"]] = row["ontology"]
        owl_term_set = set(owl_terms.items())

        provo_uri = URIRef("http://www.w3.org/ns/prov-o#")
        # provo_term_set is terms matching :
        #   [] rdfs:isDefinedBy  <http://www.w3.org/ns/prov-o#>
        provo_term_set = set([term for term in owl_term_set if term[1] == provo_uri])

        rdflib_term_set = set(
            [
                (PROV[termword], owl_terms.get(PROV[termword], None))
                for termword in dir(PROV)
            ]
        )
        self.assertLessEqual(provo_term_set, rdflib_term_set)
        self.assertGreaterEqual(owl_term_set, rdflib_term_set)
```

I won't mind making a PR for it, but it is rather slow and does not necessarily make sense to run every time, could maybe add them conditional on an environment variable like `TEST_PEDANTIC` or `TEST_SLOW`, so that if either of those are set the test runs.

**Comment by nicholascar** [comment]
Merging as the only error is the old annoying one of not being able to assign an address (i.e. not a real error).

**Pull request merged**
