### PR TITLE
feat: hextuple parser and serializer now supports anonymous graph names

### PR DESCRIPTION
**Pull request by edmondchuc**
# Summary of changes

Add support for the handling of anonymous graph names in the hextuple parser and serializer.

The previous behaviour always treated the sixth value in the tuple as the IRI of the graph name. However, as per the [hextuples spec](https://github.com/ontola/hextuples?tab=readme-ov-file#hextuples-ndjson), 

> If the graph is a blank node (i.e. anonymous), use an underscore as the URI scheme: _:myNode. (https://github.com/ontola/hextuples/issues/2). Parsers SHOULD interpret these as blank graphs, but MAY discard these if they have no support for them.

This new behaviour now inspects the start of the value and, if it sees `_:`, it will treat it as a blank node.

Tests have been added and updated to adjust for this change, including the testing of roundtripping the hextuple format.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- If the change adds new features or changes the RDFLib public API:
  
  - [ ] Created an issue to discuss the change and get in-principle agreement.
  - [ ] Considered adding an example in `./examples`.
- If the change has a potential impact on users of this project:
  
  - [x] Added or updated tests that fail without the change.
  - [ ] Updated relevant documentation to avoid inaccuracies.
  - [ ] Considered adding additional documentation.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by edmondchuc** [comment]
This is some precursor work on parsers to support skolemization at parse time.

**Comment by edmondchuc** [comment]
pre-commit.ci autofix

**Comment by edmondchuc** [comment]
There seems to be some linting/styling differences with the precommit autofix and the gha:lint rules for ruff.

**Review by ashleysommer — APPROVED** [review]

**Comment by ashleysommer** [comment]
This looks good, tests are fine and tests are passing.

**Pull request merged**
