### PR TITLE
Adding a wrapper for batching add() calls to a Graph

### PR DESCRIPTION
**Pull request by mwatts15**
- Should address RDFLib/rdflib#357

### CODE REVIEW

**Comment by nicholascar** [comment]
@mwatts15 we need to discuss this: we think the solution here to #357 should overload the `g.add()` method, so that it's seamlessly available, rather than declaring another class which may or may not be used.

**Comment by mwatts15** [comment]
Can you elaborate on this?
> overload the g.add() method, so that it's seamlessly available

**Comment by nicholascar** [comment]
Let me think about this a bit for a sec more: I'm not sure I've really worked out what I'm thinking!

**Comment by nicholascar** [comment]
Could you add a test file for this perhaps?

**Comment by nicholascar** [comment]
Close/Open Travis

**Comment by mwatts15** [comment]
> Could you add a test file for this perhaps?

Can do. As I was stubbing out tests, I realized there's some input validation I could do. Also, can support quads for conjunctive graphs pretty trivially, so will also add that.

**Comment by nicholascar** [comment]
Seems to be failing only Python2.7. If you want this in the 5.0.0 release (end of March), you'll need to pass 2.7. If you want for the 6.0.0 release (end of June), you can drop the 2.7 and 3.4 tests as we'll only be supporting 3.5+ then and forward.

**Comment by mwatts15** [comment]
I was actually looking at a problem from an rdflib-sqlalchemy user which is similar, but I realize that this PR doesn't address their use-case since they really need a proxy so they can use the wrapped Graph with just add/addN modified. 

Any objection to adding wrapt as a dependency to rdflib to implement this?

**Comment by nicholascar** [comment]
I'll merge this in for now. Not 100% sure about adding dependencies and I just raised a dependency-related Issue (#1035) so let's add this in and see the SQLAlchemy fix as a separate PR?

**Pull request merged**
