### PR TITLE
Marks some doctstrings as raw, to silence a SyntaxWarning about invalid escape sequences.

### PR DESCRIPTION
**Pull request by mr-c**
# Summary of changes

This was reported by a Debian user: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067726

Before
``` sh
$ python -c 'import rdflib.extras.external_graph_libs'
rdflib/extras/external_graph_libs.py:79: SyntaxWarning: invalid escape sequence '\*'
  """Converts the given graph into a networkx.MultiDiGraph.
rdflib/extras/external_graph_libs.py:136: SyntaxWarning: invalid escape sequence '\*'
  """Converts the given graph into a networkx.DiGraph.
rdflib/extras/external_graph_libs.py:199: SyntaxWarning: invalid escape sequence '\*'
  """Converts the given graph into a networkx.Graph.
$
```

After:
``` sh
$ python -c 'import rdflib.extras.external_graph_libs'
$
```

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [ ] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by nicholascar** [comment]
@mr-c is this PR still needed now? There have been a number of updates to the various syntax checkers in use recently.

Could you please confirm this is still relevant on Debian and, if so, I will merge.

**Comment by mr-c** [comment]
> @mr-c is this PR still needed now? There have been a number of updates to the various syntax checkers in use recently.

Hello, I'm on vacation and away from any computer. Can you run the following on the tip of the development branch? If any warnings print then yes, this PR is still needed.

`python -c 'import rdflib.extras.external_graph_libs'`

**Comment by mr-c** [comment]
> The Debian bug report seems to indicate this is fixed in RDFLib 7.0.0

It is fixed in the Debian package of `rdflib` starting with version `6.3.2-1` (the `-1` suffix is the version of the Debian package) because we added this patch ☺️ which we still used for rdflib 7.0.0

https://salsa.debian.org/python-team/packages/rdflib/-/blob/debian/debian/patches/silence_SyntaxWarnings.patch?ref_type=heads

A.k.a.
 https://sources.debian.org/src/rdflib/7.0.0-1/debian/patches/silence_SyntaxWarnings.patch/

**Comment by ashleysommer** [comment]
@nicholascar  This isn't related to linting, the warning is emitted when Python is configured to print SyntaxWarnings on import of packages. Its technically a bug in the docstrings on the RDFLib `external_graph_libs` module.  Our linters and tests don't pick it up because they have a `#noqa:` comment on them to silence the linters.

@mr-c This is a nice simple patch, I'll merge it.

**Pull request merged**
