### PR TITLE
Add @expectedFailure unit tests for #1294 and type annotations for compare.py

### PR DESCRIPTION
**Pull request by aucampia**
This is related to #1294

## Proposed Changes

  - Add type annotations for compare.py
  - Add @expectedFailure unit tests for #1294

### CODE REVIEW

**Comment by nicholascar** [comment]
@rob-metalinkage you'd better look this over

**Review by rob-metalinkage — COMMENTED** [review]
Good to have some tests - I think it would be better to characterise the tests around the expected behaviour in a systematic way that supports regression testing - rather than tests per issue, but thats a much bigger piece of work.  I'm not familiar with the @expectedFailure and how it fits into planning to _fix_ the problem - from what I read its useful to catch unexpected fixes when the code is changing.

**Comment by aucampia** [comment]
@rob-metalinkage I will update the PR to make the tests more descriptive. The idea of adding `@expectedFailure` test to the code base is to establish what behaviour should be there, even if the behaviour is not there currently, it should then make it easier for someone who is changing this or fixing this to understand the expectations of the code.

**Comment by nicholascar** [comment]
@aucampia can you finish of this PR shortly? If so, we can merge it into the 6.0.0 candidate

**Comment by aucampia** [comment]
@rob-metalinkage I added some better explanations for the tests, and tests names are also more descriptive and not issue specific.

Again this does not fix the problem, but it sets constraints on what a fix for this issue should do. The hope is that it makes it easier for whoever looks at this later.

I may look at this again in the future myself, but this at least provides a very minimal test that should pass which makes the issue easier to pinpoint, and together with type annotations makes it easier for me to see what the intent was of the original author.

**Review by nicholascar — APPROVED** [review]
Thanks for the swift work @aucampia !

**Pull request merged**
