### PR TITLE
Convert translate_algebra tests to pytest

### LINKED ISSUE #1451: Tests for translateAlgebra are not integrated with other unit tests
As far as I can tell `translateAlgebra` tests (stuff in `test/translate_algebra/...`) are not integrated with other unit tests and will not run when `run_tests.py` or `nosetests` run.

```
$ \rm -rv .venv
$ python3.7 -m venv .venv
$ .venv/bin/python3 -m pip install -r requirements.txt -r requirements.dev.txt
$ export PYTHONPATH=$(readlink -f .):$(readlink -f .venv)
$ .venv/bin/python test/translate_algebra/main.py
Traceback (most recent call last):
  File "test/translate_algebra/main.py", line 1, in <module>
    from test_base import Test, TestExecution, format_text
  File "/home/iwana/d.x/github.com/RDFLib/rdflib/test/translate_algebra/test_base.py", line 1, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
$ .venv/bin/python3 -m pip install pandas
$ .venv/bin/python test/translate_algebra/main.py
Traceback (most recent call last):
  File "test/translate_algebra/main.py", line 1, in <module>
    from test_base import Test, TestExecution, format_text
  File "/home/iwana/d.x/github.com/RDFLib/rdflib/test/translate_algebra/test_base.py", line 5, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
$ .venv/bin/python3 -m pip install tabulate
```

Furthermore it seems these tests need `pandas` and `tabulate` and seems to be expecting a file `test/config.ini` with a section `TEST`

```
$ .venv/bin/python test/translate_algebra/main.py
Executing tests ...
Traceback (most recent call last):
  File "test/translate_algebra/main.py", line 889, in <module>
    t.run_tests()
  File "/home/iwana/d.x/github.com/RDFLib/rdflib/test/translate_algebra/test_base.py", line 107, in run_tests
    logging.getLogger().setLevel(int(self.test_config.get("TEST", "log_level")))
  File "/usr/lib64/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib64/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'TEST'
```

https://github.com/RDFLib/rdflib/blob/f4e1efd17f5faf8479bc04693929ced07a172ebf/test/translate_algebra/test_base.py#L62-L65

https://github.com/RDFLib/rdflib/blob/f4e1efd17f5faf8479bc04693929ced07a172ebf/test/translate_algebra/test_base.py#L107

Ideally this should be integrated with the rest of the tests, it should run when run_tests.py runs and when drone CI runs, it should also have all dependencies in requirements.dev.txt and it should have all required config files.

The best option would be to base the test system used for translateAlgebra on python's unittest module.

See also:

 - https://github.com/RDFLib/rdflib/pull/1322 - The original PR that introduced `translateAlgebra`
 - https://github.com/RDFLib/rdflib/pull/1361 - Some fixes (not merged yet)

### PR DESCRIPTION
**Pull request by aucampia**
As far as I can tell all the tests inside test/translate_algebra
basically did the following:

```python
query_tree = parser.parseQuery(self.query_text)
query_algebra = algebra.translateQuery(query_tree)
self.query_from_algebra = translateAlgebra(query_algebra)

query_tree_2 = parser.parseQuery(self.query_from_algebra)
query_algebra_2 = algebra.translateQuery(query_tree_2)
self.query_from_query_from_algebra = translateAlgebra(query_algebra_2)
_pprint_query(self.query_from_query_from_algebra)
```

One test tried to also execute the query, but against a None valued
variable. And then there was some exception handling in specific place.

This change converts all of this to pytest using parameterization.

There are two tests that fail, and seem to also fail in the old test
structure, they are:

```python
AlgebraTest(
    "test_other__service1",
    "Test if a nested service pattern is properly translated"
    "into the query text.",
    pytest.mark.xfail(raises=RecursionError),
),
AlgebraTest(
    "test_property_path__negated_property_set",
    "Test if a negated property set gets properly translated into the query text.",
    pytest.mark.xfail(raises=TypeError, reason="fails in translateAlgebra"),
),
```

The `test_other__service1` causes some more serious issues on Windows so
it is guarded in a condition to only run it on non Windows operating
systems.

Fixes #1451

### CODE REVIEW

**Comment by aucampia** [comment]
@GreenfishK would appreciate it if you could have a look at this.

**Comment by GreenfishK** [comment]
@aucampia First of all, thank's so much for your effort and sorry that I still did not find time. If there is still something I can do, I will take time for it this weekend.
Tests: I had two ideas. The first one was to roundtrip the query as you understood correctly and to compare the normalized original query with the roundtripped normalized original query. the second one was to execute the query pairs against a currated graph and to see if they both deliver the same result. At the time of writing I did not have time to set up queries for an actual currated graph so I constructed artificial ones. That is why you found one query with such an attempt, which I thought I actually removed.

**Comment by aucampia** [comment]
> Tests: I had two ideas. The first one was to roundtrip the query as you understood correctly and to compare the normalized original query with the roundtripped normalized original query. the second one was to execute the query pairs against a currated graph and to see if they both deliver the same result. At the time of writing I did not have time to set up queries for an actual currated graph so I constructed artificial ones. That is why you found one query with such an attempt, which I thought I actually removed.

Thanks for the information and clarification, I added a comment capturing this intent now.

**Comment by nicholascar** [comment]
@GreenfishK @aucampia is ready to be merged now, as is, but then later PRs might add the curated graph tests?

**Comment by aucampia** [comment]
> @GreenfishK @aucampia is ready to be merged now, as is, but then later PRs might add the curated graph tests?

Yes, as the tests being replaced did not have these anyway. They will technically be testing something outside the scope of algebra to query translation though, so while they may be useful they are not critical and the tests here should be sufficient for testing translateAlgebra given translateQuery is working correctly.

**Review by nicholascar — APPROVED** [review]
Approval from me but waiting on a last worrd from @GreenfishK before merge

**Comment by GreenfishK** [comment]
@nicholascar @aucampia I checked the commit and it looks good to me, also the code is conciser now. Thank you!
You once asked me to add a description to https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html. I plan to do that now if it is still needed.

**Comment by nicholascar** [comment]
Thanks for the confirmation @GreenfishK, merging now. 

@GreenfishK: it would be best to add the tests for #1361 so we can clear away all test passing PRs but they yes, love to have more material for the Intro to SPARQL! I keep promising myself to sit down and to a comprehensive set of additions to documentation before each release but I'm only making progress bit-by-bit there!

**Comment by GreenfishK** [comment]
@nicholascar I am working on the tests for #1361

**Pull request merged**
