### PR TITLE
Support for rdfstar  and reasoner

### PR DESCRIPTION
**Pull request by prerak01**
# Summary of changes

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.
- [x] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [ ] Updated relevant documentation to avoid inaccuracies.
  - [ ] Considered adding additional documentation.
  - [ ] Considered adding an example in `./examples` for new features.
  - [ ] Considered updating our changelog (`CHANGELOG.md`).
- [ ] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
Some concerns:

- There is ongoing work on this, using a parser generator: https://github.com/RDFLib/rdflib-rdfstar
- I would much rather prefer using a parser generator like lark
- This should include tests from https://w3c.github.io/rdf-star/tests/
- The parser should not be using global state, make a class instead
- We don't want debug `prints()` in `rdflib/`
- This is based on string matching, which is not going to be good enough IMO, this shoudl be based on a proper grammar and parser generated from said grammar.
- Many changes are not PEP8 compatible.

**Review by aucampia — CHANGES_REQUESTED** [review]
See previous comments.

**Comment by aucampia** [comment]
Please rebase this branch onto master or merge master into this branch.

**Comment by prerak01** [comment]
ok

**Pull request closed without merging**
