### PR TITLE
allow sphinx-autodoc-typehints to be upgraded to 2.3.x

### PR DESCRIPTION
**Pull request by mr-c**
# Summary of changes

Allow installing with sphinx-autodoc-typehints version up to version 2.3.x in Python 3.9+ systems.

Currently this results in an error while building docs, hence this PR being in draft state, see https://github.com/RDFLib/rdflib/issues/2912

# Checklist

- [ ] Checked that there aren't other open pull requests for
  the same change.
- [ ] Checked that all tests and type checking passes.
- If the change adds new features or changes the RDFLib public API:
  
  - [ ] Created an issue to discuss the change and get in-principle agreement.
  - [ ] Considered adding an example in `./examples`.
- If the change has a potential impact on users of this project:
  
  - [ ] Added or updated tests that fail without the change.
  - [ ] Updated relevant documentation to avoid inaccuracies.
  - [ ] Considered adding additional documentation.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by ashleysommer** [comment]
After RDFLib v7.1.0 releases, we will drop Python 3.8 support, and from RDFLib v8.0 we have only Python 3.9+.

**Comment by ashleysommer** [comment]
@mr-c 
Are you able to please rebase your changes against the new changes in the `main` branch, you will no longer need the `python >= 3.9` conditionals in the pyproject.toml.

**Comment by mr-c** [comment]
> @mr-c Are you able to please rebase your PR against the new changes in the `main` branch, you will no longer need the `python >= 3.9` conditionals in the pyproject.toml.

Done, thank you for the reminder. The docs build fails still, as before: https://github.com/RDFLib/rdflib/actions/runs/11699448011/job/32581466682?pr=2913#step:9:2223

**Comment by ashleysommer** [comment]
Closing because https://github.com/RDFLib/rdflib/pull/2974 and https://github.com/RDFLib/rdflib/pull/2973 fix this.

**Pull request closed without merging**
