### PR TITLE
Fix missing query string params in sparqlconnector when using POST method 

### PR DESCRIPTION
**Pull request by davidandreoletti**
# Summary of changes

The  SPARQLConnector instance created by a SPARQLStore instance providing endpoint url + **query string params** using POST method did not append the query string to endpoint url.

This PR fixes this.

Backward compatible: yes.

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.
- [x] Checked that all tests and type checking passes.

### CODE REVIEW

**Review by aucampia — APPROVED** [review]
Thank you for the PR @davidandreoletti. I updated your code slightly to cover the edge case where `default-graph-uri` is set, and I also changed your test to a parameterized test which checks for this case.

I also made some other slight cosmetic changes to the test.

**Comment by aucampia** [comment]
I will merge tomorrow if there is no further feedback.

**Comment by davidandreoletti** [comment]
> I will merge tomorrow if there is no further feedback.

Sounds good. Thanks.

**Comment by davidandreoletti** [comment]
@aucampia Last release (v6.2.0) was published around July 2022. What's the most probable timeline for the next release ?

**Pull request merged**
