### PR TITLE
test: rework RDF/XML test suite

### PR DESCRIPTION
**Pull request by aucampia**
# Summary of changes

This patch reworks the RDF/XML test suite to use the new DAWG manifest
processor. It also sync the RDF/XML test data with the upstream source
so we report on the official test files.

However, some tests are commented out
in upstream (i.e. <https://www.w3.org/2013/RDFXMLTests/manifest.ttl>), and
without these tests our coverage decreases. The commented out tests are
for [non-normative behavior relating to XML Literals](https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-XML-literals).

To keep the coverage the same these non-normative tests were moved to a separate test suite `test/data/suites/w3c/rdf-xml-non-normative/` and are reported on in a separate report file, `test_reports/rdflib_w3c_rdfxml_non_normative-HEAD.ttl`.

Other changes:
- Add RDF/XML EARL reports generated with new test suites.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
Checking the reason for decreased coverage now, I may add some more tests to get coverage back to what it was.

**Comment by aucampia** [comment]
> Checking the reason for decreased coverage now, I may add some more tests to get coverage back to what it was.

Okay, when un-commenting the tests the uncovered lines are covered again, changing branch to do this now.

**Review by gjhiggins — APPROVED** [review]
truly heroic! great to have a coherent and consistent approach to the W3C test suite.

**Comment by aucampia** [comment]
I got feedback on the issue I raised regarding the commented out tests: https://github.com/w3c/rdf-tests/issues/80

These tests are for non-normative behavior, and as such should not be part of the official test suite.

I moved these to a separate test suite in our source tree in `test/data/suites/w3c/rdf-xml-non-normative/` and restored the content of `test/data/suites/w3c/rdf-xml/` to exactly match upstream. They will also be reported on in a separate report file.

**Pull request merged**
