### PR TITLE
Fix for issue #923, Result.parse with content_type that includes a ;charset=

### PR DESCRIPTION
**Pull request by gordom6**

### CODE REVIEW

**Comment by jimmccusker** [comment]
@joernhees, is there a holdup on this?

**Comment by nicholascar** [comment]
Close/open Travis

**Comment by nicholascar** [comment]
Hi @gordom6 & @jimmccusker there is a minor hold up here: You'll see the Travis build is failing for Python 2.7 and we have to maintain compatibility with Python 2.7 for the 5.0.0 release that this will be part of if we can get this merged soon.

The error in Travis is from the new test function:

```
ERROR: test.test_issue923.test_issue_923
----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/build/RDFLib/rdflib/test/test_issue923.py", line 34, in test_issue_923

    with StringIO(RESULT_SOURCE) as result_source:

TypeError: initial_value must be unicode or None, not str
```

Could one of you please patch this for Py2.7 and then we'll merge? Thanks, Nick

**Comment by jimmccusker** [comment]
Why are we still supporting Python 2 when it's EOL? Especially when this is a major revision?

**Comment by white-gecko** [comment]
As pointed out in https://groups.google.com/forum/#!msg/rdflib-dev/Qt4UeYOBWdg/FXXzQEZ_AAAJ we are going to drop Python 2 support in the 6.0.0 release. Currently there is still a future python 2.7 release planed for 2020-04 (https://www.python.org/dev/peps/pep-0373/).

**Pull request merged**
