### PR TITLE
Clean up documentation

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This patch series catches some minor copy-editing and Git nits.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Hm, CI failure might be a spurious Fuseki issue?

**Comment by aucampia** [comment]
@ajnelson-nist it is - seems fuseki is just too slow on MacOS - timeout was increased to 30 seconds but still too slow.

**Comment by aucampia** [comment]
Will remove it from MacOS this week.

**Review by aucampia — APPROVED** [review]

**Review by nicholascar — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
