### PR TITLE
remove deprecated Graph methods

### PR DESCRIPTION
**Pull request by gjhiggins**
along with the associated tests and remove obsoleted references from Resource docstring.

Fixes # Implements asserted deprecation statements  “xxx is deprecated and will be removed in rdflib 6.0.0."

## Proposed Changes
  - Remove Graph.label()
  - Remove Graph.preferredLabel()
  - Remove Graph.comment()
  - Remove Graph.seq()
  - Remove Graph.load()

### CODE REVIEW

**Comment by aucampia** [comment]
Looks good, I made a PR to remove some additional uses of these methods from `Resource`: https://github.com/DOACC/rdflib/pull/1

**Comment by gjhiggins** [comment]
> Looks good, I made a PR against your branch to remove some additional uses of these methods from `Resource`: [DOACC#1](https://github.com/DOACC/rdflib/pull/1)

Ah-hah, you expose my over-reliance on the test suite. Good catch, thanks,

**Review by aucampia — APPROVED** [review]

**Review by veyndan — APPROVED** [review]

**Comment by nicholascar** [comment]
I'll just hold off on this one until after 6.0.3. Really it should be merged in for a 6.1.0 or a 7.0.0 release.

**Comment by gjhiggins** [comment]
Completely messed up the DOACC-located clone, basically irrecoverable, need to re-issue this PR from fresh clone, sorry.

**Pull request closed without merging**
