### PR TITLE
Feature/forward version to 6.0.0-alpha

### PR DESCRIPTION
**Pull request by white-gecko**
## Proposed Changes

  - Update the version string to allow installations from the git repo and let pip know, it is newer than the pypi release
  - Will allow install with `pip install git+https://github.com/rdflib/rdflib@master` over a pypi installation

### CODE REVIEW

**Comment by nicholascar** [comment]
Thanks for this @white-gecko - super useful to have GitHub tell us the master is more recent than the release.

I wonder why the Drone 3.8 test failed? Strange that Drone seems unable to clone the repo since it did it for 2.6 & 3.7
Open/close the PR to restart tests.

**Comment by nicholascar** [comment]
Open/close to restart Drone

**Comment by nicholascar** [comment]
Open/Close seems not to work for Drone tests. @ashleysommer, can you please restart the Drone tests here?

**Comment by white-gecko** [comment]
I did restart the test but now it can't clone for any of them.

Maybe it is, that I accidentally pushed the branch to the rdflib repo as well and then deleted the branch on the rdflib repo again?

**Comment by nicholascar** [comment]
Sorry to be a pain but can you close this PR and re-issue it "clean"? Then we will know if it was a brach addition/removal issue.

**Pull request closed without merging**
