### PR TITLE
style: fix isort config

### PR DESCRIPTION
**Pull request by aucampia**
# Summary of changes

`isort` was misconfigured to only touch `*.{pyw,pyi}` files.

This patch fixes isort config so that it actually does sort imports.

It also removes the attempt to ignore the test directory.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
basically the same as https://github.com/RDFLib/rdflib/pull/1798 - again would like to know what people think, I think it is useful but would be fine to leave it also if it bothers anyone too much.

**Comment by aucampia** [comment]
Okay actually isort is doing nothing, so this PR will be basically just adding isort with working config.

**Comment by aucampia** [comment]
As with https://github.com/RDFLib/rdflib/pull/1798 - if everyone is in agreement I will rebase, comment "pre-commit.ci autofix" and merge.

**Review by nicholascar — APPROVED** [review]
Good to have it actually touch the Python files, given that's what it's for!

**Comment by aucampia** [comment]
@gjhiggins good to have your feedback here also. Don't want to make anyones life harder, so if we should look at ways of making these things less onerous on developers we should look at it.

**Review by gjhiggins — APPROVED** [review]

**Comment by aucampia** [comment]
pre-commit.ci autofix

**Pull request merged**
