### PR TITLE
do not write prefix for empty graph id, fix #2154

### LINKED ISSUE #2154: can't get rid of default prefix definition in trig serialization
I have a trig file with just one graph like this:

```trig
@prefix adm: <http://purl.bdrc.io/ontology/admin/> .
@prefix bda: <http://purl.bdrc.io/admindata/> .
@prefix bdg: <http://purl.bdrc.io/graph/> .

bdg:W1NLM5228 {
    bda:W1NLM5228 a adm:AdminData ;
        adm:status bda:StatusReleased .
}
```

In my use case I need to be able to read it, modify it and then write it with the same prefix definitions, but when I do something very simple like

```python
import rdflib
from rdflib import Literal, Graph, Dataset, URIRef
import os

ds = Dataset()
ds.parse("bug.trig", format="trig", publicID=URIRef("http://purl.bdrc.io/graph/W1NLM5228"))
ds.remove_graph(URIRef("urn:x-rdflib:default")) # doesn't work
ds.serialize(filepath+"-bug", format="trig")
```

the output I get is

```trig
@prefix adm: <http://purl.bdrc.io/ontology/admin/> .
@prefix bda: <http://purl.bdrc.io/admindata/> .
@prefix bdg: <http://purl.bdrc.io/graph/> .
@prefix ns1: <urn:x-rdflib:> .

bdg:W1NLM5228 {
    bda:W1NLM5228 a adm:AdminData ;
        adm:status bda:StatusReleased .
}
```

and I seem unable to remove the `ns1: <urn:x-rdflib:>` prefix definition. Is there any way to do so? Thanks!

### PR DESCRIPTION
**Pull request by eroux**
# Summary of changes

Since the names of empty graphs do not appear in the serialization, do not consider them for namespace issues.

fixes #2154 

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.
- [ ] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [ ] Updated relevant documentation to avoid inaccuracies.
  - [ ] Considered adding additional documentation.
  - [ ] Considered adding an example in `./examples` for new features.
  - [ ] Considered updating our changelog (`CHANGELOG.md`).
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by eroux** [comment]
Thanks for the merge!

**Comment by aucampia** [comment]
Sorry for the delay in review, I will try check by the weekend.

**Review by aucampia — APPROVED** [review]
Change looks good to me. For posterity sake, the reason this addresses the problem is that it avoids `TurtleSerializer.getQName` which would add the namespace of a each graph in a dataset to the collection of namespaces to serialize.

**Comment by eroux** [comment]
thanks a lot!

**Pull request merged**
