### PR TITLE
rd2dot Escape HTML in node label and URI text

### LINKED ISSUE #1208: rdf2dot ampersand escape
rdf2dot is not escaping html characters in places it should. Here is minimum reproducible example:

```py
from rdflib import URIRef, Literal
from rdflib.namespace import DC
subj = URIRef('eg://org/?foo=bar&baz=bux')
pred = URIRef('eg://org/predicate')
obj = URIRef('eg://org/object')

g = rdflib.Graph()
g.add((subj, pred, obj))
g.add((subj, DC.title, Literal('This & That')))
out = io.StringIO()
rdf2dot(g, out, opts={display})
out.getvalue()
```

outputs:
```
digraph { 
 node [ fontname="DejaVu Sans" ] ; 
	node0 -> node1 [ color=BLACK, label=< <font point-size='10' color='#336633'>ns1:predicate</font> > ] ;
# eg://org/?foo=bar&baz=bux node0
node0 [ shape=none, color=black label=< <table color='#666666' cellborder='0' cellspacing='0' border='1'><tr><td colspan='2' bgcolor='grey'><B>This & That</B></td></tr><tr><td href='eg://org/?foo=bar&baz=bux' bgcolor='#eeeeee' colspan='2'><font point-size='10' color='#6666ff'>eg://org/?foo=bar&baz=bux</font></td></tr><tr><td align='left'>ns2:title</td><td align='left'>&quot;This &amp; That&quot;</td></tr></table> > ] 
# eg://org/object node1
node1 [ shape=none, color=black label=< <table color='#666666' cellborder='0' cellspacing='0' border='1'><tr><td colspan='2' bgcolor='grey'><B>object</B></td></tr><tr><td href='eg://org/object' bgcolor='#eeeeee' colspan='2'><font point-size='10' color='#6666ff'>eg://org/object</font></td></tr></table> > ] 
}
```

Which is invalid DOT in several places:
 - `<B>This & That</B>`
 - `eg://org/?foo=bar&baz=bux</font>`

### PR DESCRIPTION
**Pull request by blake-regalia**
Fixes #1208 

## Proposed Changes
 - escapes HTML in the node label
 - escapes HTML in the URI text

### CODE REVIEW

**Comment by nicholascar** [comment]
Open Close Travis

**Review by nicholascar — APPROVED** [review]
Looks good to me. The Travis test failure is due only to connection issues in Travis, not anything from the code changes so I approve. Awaiting second review.

**Comment by white-gecko** [comment]
Actually now I tried to reproduce your example from #1208 resp. my version https://github.com/RDFLib/rdflib/issues/1208#issuecomment-751780847 and I get:

```
Error: not well-formed (invalid token) in line 1 
... <B>This & That ...
in label of node node0
```

the result is:

```
digraph { 
 node [ fontname="DejaVu Sans" ] ; 
	node0 -> node1 [ color=BLACK, label=< <font point-size='10' color='#336633'>ns1:predicate</font> > ] ;
# eg://org/?foo=bar&baz=bux node0
node0 [ shape=none, color=black label=< <table color='#666666' cellborder='0' cellspacing='0' border='1'><tr><td colspan='2' bgcolor='grey'><B>This & That</B></td></tr><tr><td href='eg://org/?foo=bar&baz=bux' bgcolor='#eeeeee' colspan='2'><font point-size='10' color='#6666ff'>eg://org/?foo=bar&baz=bux</font></td></tr><tr><td align='left'>ns2:title</td><td align='left'>&quot;This &amp; That&quot;</td></tr></table> > ] 
# eg://org/object node1
node1 [ shape=none, color=black label=< <table color='#666666' cellborder='0' cellspacing='0' border='1'><tr><td colspan='2' bgcolor='grey'><B>object</B></td></tr><tr><td href='eg://org/object' bgcolor='#eeeeee' colspan='2'><font point-size='10' color='#6666ff'>eg://org/object</font></td></tr></table> > ] 
}
```

so there is still an unescaped &

**Comment by white-gecko** [comment]
Maybe it would be good to have the example as test

**Comment by white-gecko** [comment]
I think I did't acutally test the fixed version, now I did bot got the following error an result:

```
Error: not well-formed (invalid token) in line 1 
... <tr><td href='eg://org/?foo=bar&baz=bux' bgcolor='#eeeeee' colspan='2'> ...
in label of node node0
```

```
digraph { 
 node [ fontname="DejaVu Sans" ] ; 
	node0 -> node1 [ color=BLACK, label=< <font point-size='10' color='#336633'>ns1:predicate</font> > ] ;
# eg://org/?foo=bar&baz=bux node0
node0 [ shape=none, color=black label=< <table color='#666666' cellborder='0' cellspacing='0' border='1'><tr><td colspan='2' bgcolor='grey'><B>This &amp; That</B></td></tr><tr><td href='eg://org/?foo=bar&baz=bux' bgcolor='#eeeeee' colspan='2'><font point-size='10' color='#6666ff'>eg://org/?foo=bar&amp;baz=bux</font></td></tr><tr><td align='left'>ns2:title</td><td align='left'>&quot;This &amp; That&quot;</td></tr></table> > ] 
# eg://org/object node1
node1 [ shape=none, color=black label=< <table color='#666666' cellborder='0' cellspacing='0' border='1'><tr><td colspan='2' bgcolor='grey'><B>object</B></td></tr><tr><td href='eg://org/object' bgcolor='#eeeeee' colspan='2'><font point-size='10' color='#6666ff'>eg://org/object</font></td></tr></table> > ] 
}
```

**Comment by white-gecko** [comment]
For me it is not very clear, how actually an `&` should be encoded for dot within a hyperreference.

@blake-regalia and @nicholascar how was the output of your tests?

**Comment by blake-regalia** [comment]
Hmm, yes it seems that the href attribute value _should_ also be escaped:

> As HTML strings are processed like HTML input, any use of the ", &, <, and > characters in literal text or in attribute values need to be replaced by the corresponding escape sequence. For example, if you want to use & in an href value, this should be represented as &amp;.

https://graphviz.org/doc/info/shapes.html#html

But it seems no matter what I do, the DOT parsers cannot tolerate an ampersand in the href value whether or not it is in an HTML escape sequence `&amp;`. This could be a bug in those DOT parser implementations... I haven't found any hits on search relating to this exact problem.

For reference, here is the complete self-contained minimum example snippet:
```py
import io
from rdflib import URIRef, Literal
from rdflib.namespace import DC
subj = URIRef('eg://org/?foo=bar&baz=bux')
pred = URIRef('eg://org/predicate')
obj = URIRef('eg://org/object')

g = rdflib.Graph()
g.add((subj, pred, obj))
g.add((subj, DC.title, Literal('This & That')))
out = io.StringIO()
rdf2dot(g, out)
print(out.getvalue())
```

**Pull request merged**
