### PR TITLE
Resolved issue regarding relative URI

### PR DESCRIPTION
**Pull request by UditArora2000**
Issue number - 677

# Summary of changes

# Checklist

- [ ] Checked that there aren't other open pull requests for
  the same change.
- [ ] Added tests for any changes that have a runtime impact.
- [ ] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [ ] Updated relevant documentation to avoid inaccuracies.
  - [ ] Considered adding additional documentation.
  - [ ] Considered adding an example in `./examples` for new features.
  - [ ] Considered updating our changelog (`CHANGELOG.md`).
- [ ] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by gjhiggins** [comment]
Too early to merge yet, it's as-yet-unfinished code isn't it? And your proposed change has a run-time impact which should be explicitly tested.

**Review by aucampia — CHANGES_REQUESTED** [review]
- This has no tests.
- This contains debugging code.
- See response from @gjhiggins

**Comment by aucampia** [comment]
Please rebase this branch onto master or merge master into this branch.

**Comment by aucampia** [comment]
If there is nothing further on this PR I will close it.

**Comment by aucampia** [comment]
Closing this PR due to inactivity, feel free to open it again if you continue working on it again.

**Pull request closed without merging**
