### PR TITLE
test: Add tests for SPARQL parsing and serialization

### PR DESCRIPTION
**Pull request by aucampia**
# Summary of changes

This patch adds some tests for SPARQL serialization and deserialization
with checks based on round tripping where possible.

Some of these tests are expected failures in that they seem to pass fo
some parsers or serializers, but not others. If there is agreement on
what parameters should be supported we can fix the parsers and
serializers to actually support them.

There are also xfails for the handling of string paths on windows, as
this seems to fail for all serializers.

Other changes:
 - style: apply black on `test/test_graph/test_graph.py` and `test/test_n3.py`. There are no other changes to these files other than applying black, and it is done by pre-commit.ci bot.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
The most controversial thing here, and what is most in need of review, is the expected failures:

https://github.com/RDFLib/rdflib/blob/9b5ac57fa12a2cb1cf39ad1fae75bdfa75785873/test/test_sparql/test_result.py#L186-L201

Some parsers support the encodings, and some parsers support TEXT_IO, and some support BINARY_IO. In my view all parsers should support all of them, and all of those tests should pass, so the expected failures are correct in that they denote known issues, and we can fix the issues without breaking interfaces. I'm happy to extend support once we are in agreement there.

**Comment by aucampia** [comment]
Okay and it seems path handling completely fails on windows, adding xfails for that also, and will fix those also in a future patch.

**Review by gjhiggins — APPROVED** [review]
Solid stuff, useful to have.

**Comment by aucampia** [comment]
pre-commit.ci autofix

**Comment by aucampia** [comment]
rebased now onto master, two files in diff are result of pre-commit.ci applying black.

**Comment by aucampia** [comment]
Merged as this is only adding tests, not changing any tests. The xfail marked tests also seem valid as they pass for some parsers and some operating systems. Happy to adjust them in future PRs though.

**Pull request merged**
