### PR TITLE
feat: update DOAP namespace

### LINKED ISSUE #2811: regenerate _DOAP.py
The definition at http://usefulinc.com/ns/doap has been updated since the previous generation (for example it now contains `security-contact` and `security-policy` properties).

Unfortunately when I `python3 ./rdflib/tools/defined_namespace_creator.py doap.xml http://usefulinc.com/ns/doap# DOAP` the generated result does not look correct to me - but perhaps I'm misusing it?

### PR DESCRIPTION
**Pull request by raboof**
# Summary of changes

Including updates to `rdflib/tools/defined_namespace_creator.py` so fewer manual changes are needed.

Fixes #2811

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Review by nicholascar — APPROVED** [review]
Great to see the defined_namespace_creator updated and used to update one of the DefinedNamespaces RDFLib ships with by a non-maintainer, thanks again @raboof!

**Comment by ashleysommer** [comment]
@nicholascar Looks like required tests were not run on this PR, it introduced 6 `mypy` typing errors, that are now in `main` branch, affecting all other PRs.

**Comment by raboof** [comment]
ouch, sorry about that, I'll hvae a look

**Comment by raboof** [comment]
can you clarify how you invoke mypy? When I `poetry run mypy --show-error-context --show-error-codes` as described in https://rdflib.readthedocs.io/en/latest/developers.html#running-static-checks I'm getting errors in code I didn't change as well:

```
Creating virtualenv rdflib-MH8QKPnW-py3.12 in /home/aengelen/.cache/pypoetry/virtualenvs
rdflib/query.py:160: error: Unused "type: ignore[type-var]" comment  [unused-ignore]
rdflib/graph.py:1785: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:1829: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2000: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2003: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2798: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2817: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2820: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2987: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/graph.py:2990: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/plugins/sparql/operators.py: note: In function "simplify":
rdflib/plugins/sparql/operators.py:991: error: Statement is unreachable  [unreachable]
rdflib/plugins/sparql/algebra.py: note: In function "_traverse":
rdflib/plugins/sparql/algebra.py:414: error: Statement is unreachable  [unreachable]
rdflib/plugins/sparql/algebra.py:421: error: Statement is unreachable  [unreachable]
rdflib/plugins/sparql/algebra.py: note: In function "_traverseAgg":
rdflib/plugins/sparql/algebra.py:439: error: Statement is unreachable  [unreachable]
rdflib/tools/defined_namespace_creator.py: note: In function "make_dn_file":
rdflib/tools/defined_namespace_creator.py:148: error: Argument 1 to "len" has incompatible type "Iterable[str]"; expected "Sized"  [arg-type]
rdflib/plugins/sparql/results/xmlresults.py:257: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/plugins/sparql/results/xmlresults.py:287: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/plugins/parsers/trix.py: note: In member "startElementNS" of class "TriXHandler":
rdflib/plugins/parsers/trix.py:108: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
rdflib/plugins/parsers/trix.py:108: error: Argument 1 to "getValue" of "AttributesImpl" has incompatible type "Tuple[str, str]"; expected "str"  [arg-type]
rdflib/plugins/parsers/trix.py:113: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
rdflib/plugins/parsers/trix.py:125: error: Incompatible types in assignment (expression has type "str", variable has type "None")  [assignment]
rdflib/plugins/parsers/trix.py:125: error: Argument 1 to "getValue" of "AttributesImpl" has incompatible type "Tuple[str, str]"; expected "str"  [arg-type]
rdflib/plugins/parsers/trix.py: note: In member "parse" of class "TriXParser":
rdflib/plugins/parsers/trix.py:287: error: "ContentHandler" has no attribute "preserve_bnode_ids"  [attr-defined]
test/test_namespace/test_definednamespace_creator.py: note: In function "test_get_target_namespace_elements":
test/test_namespace/test_definednamespace_creator.py:172: error: Statement is unreachable  [unreachable]
test/test_extras/test_shacl_extras.py:215: error: Unused "type: ignore" comment  [unused-ignore]
rdflib/plugins/parsers/rdfxml.py: note: In member "startElementNS" of class "RDFXMLHandler":
rdflib/plugins/parsers/rdfxml.py:184: error: No overload variant of "get" of "AttributesImpl" matches argument types "Tuple[str, str]", "None"  [call-overload]
rdflib/plugins/parsers/rdfxml.py:184: note: Possible overload variants:
rdflib/plugins/parsers/rdfxml.py:184: note:     def get(self, name: str, alternative: None = ...) -> Optional[str]
rdflib/plugins/parsers/rdfxml.py:184: note:     def get(self, name: str, alternative: str) -> str
rdflib/plugins/parsers/rdfxml.py:201: error: No overload variant of "get" of "AttributesImpl" matches argument types "Tuple[str, str]", "None"  [call-overload]
rdflib/plugins/parsers/rdfxml.py:201: note: Possible overload variants:
rdflib/plugins/parsers/rdfxml.py:201: note:     def get(self, name: str, alternative: None = ...) -> Optional[str]
rdflib/plugins/parsers/rdfxml.py:201: note:     def get(self, name: str, alternative: str) -> str
rdflib/plugins/parsers/rdfxml.py: note: In member "convert" of class "RDFXMLHandler":
rdflib/plugins/parsers/rdfxml.py:280: error: Statement is unreachable  [unreachable]
rdflib/plugins/parsers/rdfxml.py: note: In member "literal_element_start" of class "RDFXMLHandler":
rdflib/plugins/parsers/rdfxml.py:593: error: Incompatible types in assignment (expression has type "str", variable has type "Tuple[str, str]")  [assignment]
rdflib/plugins/parsers/rdfxml.py: note: In member "parse" of class "RDFXMLParser":
rdflib/plugins/parsers/rdfxml.py:646: error: "ContentHandler" has no attribute "preserve_bnode_ids"  [attr-defined]
test/test_literal/test_literal.py:54: error: Untyped decorator makes function "clear_bindings" untyped  [misc]
test/test_literal/test_literal.py:96: error: Untyped decorator makes function "test_cant_pass_invalid_lang" untyped  [misc]
test/test_literal/test_literal.py:118: error: Untyped decorator makes function "test_ill_typed_literals" untyped  [misc]
test/test_literal/test_literal.py:172: error: Untyped decorator makes function "test_literal_addsub" untyped  [misc]
test/test_literal/test_literal.py:646: error: Untyped decorator makes function "test_numeric_literals" untyped  [misc]
test/test_literal/test_literal.py:833: error: Untyped decorator makes function "test_literal_construction_value_class" untyped  [misc]
test/test_literal/test_literal.py:944: error: Untyped decorator makes function "test_literal_construction" untyped  [misc]
test/test_literal/test_literal.py:1015: error: Untyped decorator makes function "test_global_normalize" untyped  [misc]
Found 38 errors in 11 files (checked 394 source files)
```

**Comment by raboof** [comment]
fixed two things in #2879, happy to fix more but it's not clear which ones were introduced by my changes.

**Comment by ashleysommer** [comment]
@raboof Thanks for addressing this.
Looks like there were only two (not six) errors introduced in this PR that are affecting mypy. (the other 4 I saw were coming from my other testing branch).
These are the two:
```
 poetry run python -m mypy --show-error-context --show-error-codes --junit-xml=test_reports/3.8-ubuntu-latest-mypy-junit.xml
  rdflib/tools/defined_namespace_creator.py: note: In function "make_dn_file":
  rdflib/tools/defined_namespace_creator.py:148: error: Argument 1 to "len" has incompatible type "Iterable[str]"; expected "Sized"  [arg-type]
  test/test_namespace/test_definednamespace_creator.py: note: In function "test_get_target_namespace_elements":
  test/test_namespace/test_definednamespace_creator.py:172: error: Statement is unreachable  [unreachable]
  Found 2 errors in 2 files (checked 398 source files)
```
It appears these are the two you've addressed in #2879

**Pull request merged**
