### PR TITLE
Generate random string suffixes for unique prefixes

### PR DESCRIPTION
**Pull request by gtfierro**
The grammar of Turtle does not allow numbers in the prefixes (https://www.w3.org/TR/turtle/#grammar-production-PN_PREFIX). The current generation of prefixes in the case of prefix collision uses numbers which are incremented until an unused prefix is found. Unfortunately these generated prefixes fail to parse on stricter Turtle parsers (such as oxigraph's rio). The new method should generate random Turtle-compliant prefixes.

Before:

```
# data.ttl
@prefix1: <urn:abcdef/> .
```

After:

```
# data.ttl
@prefixAGHLEISPAW: <urn:abcdef/>
```

Two questions:
1. I am open to any alternative method for generating unique prefixes --- I just chose something that I thought would work.
2. What tests should I write for this, if any? The current Turtle parser is fairly permissive which I don't really feel needs to change, so what is there to verify in the tests other than the fact that a unique prefix is still generated? I can't find any tests that verify this behavior though

# Summary of changes

Changed the algorithm for generating unique prefixes to use random 10-char strings rather than an incrementing integer.

# Checklist

- [X] Checked that there aren't other open pull requests for
  the same change.
- [ ] Added tests for any changes that have a runtime impact.
- [X] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [ ] Updated relevant documentation to avoid inaccuracies.
  - [ ] Considered adding additional documentation.
  - [ ] Considered adding an example in `./examples` for new features.
  - [ ] Considered updating our changelog (`CHANGELOG.md`).
- [ ] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by gtfierro** [comment]
I see a problem now with the tests -- I'll see if I can find a nice way to make the ID generation deterministic

**Comment by gtfierro** [comment]
Actually, I believe I've misinterpreted the Turtle spec --- I have other prefixes with numbers in them that parse fine. I will re-open once I determine the actual issue

**Comment by aucampia** [comment]
@gtfierro don't hesitate to ask on gitter either:

- https://gitter.im/RDFLib/rdflib
- https://gitter.im/linkeddata/chat

**Comment by gtfierro** [comment]
Thanks! Appreciate it

**Pull request closed without merging**
