### PR TITLE
Added DateTime arithmetic operations for Literals - Extension of #629

### PR DESCRIPTION
**Pull request by Akash-Sharma-1**
This PR adds some additional set of operations - dateTime / date / time subtraction to the Literals of RDFLib. This is an extension to the #629 issue of adding these operations to Literals in addition to the SPARQL queries.

### CODE REVIEW

**Comment by JervenBolleman** [comment]
@Akash-Sharma-1 thank you! it looks correct to me.

**Comment by nicholascar** [comment]
Hi @Akash-Sharma-1, this looks great *but*, what happens for other Literals that are not dates? Your function returns `None` fro all non dates but since you've declared a `__sub__` function in term, we (maintainers) are concerned that this might override normal Python subtraction. 

Can you please add a couple of tests to test_literal to show that this function doesn't bread integer, float and decimal subtraction? If so, we will merge in.

**Comment by FlorianLudwig** [comment]
@nicholascar I would suggest to throw a `TypeError` if subtraction is not supported for the types in question. That's what python does for other types, e.g. subtracting two strings.

**Comment by gjhiggins** [comment]
Rebased and committed in https://github.com/RDFLib/rdflib/pull/1870

**Pull request closed without merging**
