### PR TITLE
Speedup notation3 only

### PR DESCRIPTION
**Pull request by rchateauneu**
cherry picked from commit 9652eca3e9557e728879c6339c752b8451ecd47f
cherry picked from commit 3597d555c780404180b4295a1a53b742a3ca1765

### CODE REVIEW

**Comment by FlorianLudwig** [comment]
@rchateauneu still love this work :)

Same as the first two MRs! Thanks a lot.

As @white-gecko [asked](https://github.com/RDFLib/rdflib/pull/1266#issuecomment-787947011) could you add a unit test to cover the additional code paths?

**Comment by rchateauneu** [comment]
__"unit_ test to cover the additional code paths"_
With pleasure but I cannot see the code lines on:
https://coveralls.io/builds/37622816/source?filename=rdflib%2Fplugins%2Fstores%2Fmemory.py#L449

It says:
__"Source Not Available"_

At least I can start with this one:
https://coveralls.io/builds/37530950/source?filename=rdflib%2Fplugins%2Fparsers%2Fnotation3.py

Probably I should first setup a https://coveralls.io account : This is what I am doing now.

**Comment by white-gecko** [comment]
You should not need an account for this. That is strange that the files are not visible anymore.

**Comment by white-gecko** [comment]
@rchateauneu you can execute the tests locally with

    PYTHONWARNINGS=default nosetests --with-timer --timer-top-n 42 --with-coverage --cover-tests

after the test were executed you can generate a coverage report with

    coverage html

in the newly created directory you will find an `index.html` which you can open in the browser, where you can also explore the coverage of each individual file and its lines.

**Review by nicholascar — APPROVED** [review]
As with other @rchateauneu PRs: this seems to be sensible but is not passing all tests

**Comment by white-gecko** [comment]
@nicholascar I have created a pull-request, that combines the commits from the original PR with the tok commit cherry picked in: https://github.com/RDFLib/rdflib/pull/1272 also the test are successful there. I suggest to continue on this one. The last thing we were looking for are new tests for the parser, but maybe passing the current tests is ok already, what do you think?

**Comment by rchateauneu** [comment]
> 
> 
> @rchateauneu you can execute the tests locally with
> 
> ```
> PYTHONWARNINGS=default nosetests --with-timer --timer-top-n 42 --with-coverage --cover-tests
> ```
> 
> after the test were executed you can generate a coverage report with
> 
> ```
> coverage html
> ```
> 
> in the newly created directory you will find an `index.html` which you can open in the browser, where you can also explore the coverage of each individual file and its lines.

Which nosetests version are you using please ? Mine is 1.3.7 and I get the error message:
```
nosetests3: error: Error reading config file 'setup.cfg': no such option 'with-doctest-ignore-unicode'
```
... and it does not want the option --with-timer

Thanks

**Pull request closed without merging**
