### PR TITLE
update setup.py to include requests needed by Graph.parse()

### LINKED ISSUE #1122: requests not included in setup.py
although requests is defined in  requirements.txt it is not in setup.py and hence not picked up by pip install

### PR DESCRIPTION
**Pull request by rob-metalinkage**
Fixes #1122

## Proposed Changes
updates setup.py

suggest reviewing requirements.txt and setup.py and syncing.
  -
  -
  -

### CODE REVIEW

**Comment by tgbugs** [comment]
This should not be merged per https://github.com/RDFLib/rdflib/pull/969 and https://github.com/RDFLib/rdflib/issues/1035. The correct solution is to install via `pip install rdflib[sparql]`. requests is not a core dependency.

**Comment by rob-metalinkage** [comment]
i piut this  comment on #1122 

See the direction (pip install rdflib[sparql]) ,  fair enough...

but a few things seem off -

there seems to be inconsistency between requirements.txt and setup.py (and not sure if this is a good thing to have similar info in both places anyway?)
Parsing a graph from a HTTP request has nothing to do with SPARQL - so this isnt very intuitive a solution
probably the parse module should report a sensible error with the correct import suggestion if you ask it for a HTTP source and it doesnt have the install available
the documentation for parse is quite explicit HTTP is supported without any mention of the requirement.
I think all these things need to be addressed for the proposed solution to be acceptible.

**Comment by tgbugs** [comment]
Unless something changed very recently in the internals (which my review of the commit logs it did not), rdflib doesn't depend on requests for fetching http resources.

**Comment by ashleysommer** [comment]
the `requests` library is only used in two locations in `rdflib`.

Here: https://github.com/RDFLib/rdflib/blob/e4fe0fdbd4de7e1183418f302315b51a14602e03/rdflib/plugins/sparql/evaluate.py#L316-L318

And here: https://github.com/RDFLib/rdflib/blob/e4fe0fdbd4de7e1183418f302315b51a14602e03/rdflib/plugins/stores/sparqlconnector.py#L60

The only reason you would need `requests` when doing `Graph.parse()` is if you have configured your Graph to use the sparqlconnector backend.

The correct solution here would be to take the requirement out of `requirements.txt` I think it was put there accidentally.

I've been experimenting with a way of eliminating the need for `requests` in plugins/sparql/evaluate.py (by using the built-in python3 urllib.requests library), but it looks like it cannot be avoided in plugins/stores/sparqlconnector.py due to the use of a persistent Session per thread.

**Comment by rob-metalinkage** [comment]
So the HTTP request from parse works fine without requests? If so good and the doco is fine.

**Comment by white-gecko** [comment]
Ok, so we can close this I guess.

**Pull request closed without merging**
