### PR TITLE
Fix passing ConjunctiveGraph as namespace_manager

### PR DESCRIPTION
**Pull request by mielvds**
# Summary of changes

- passes the `NamespaceManager` of the `ConjunctiveGraph` as namespace_manager of the `Graph` created by the `get_context()` method instead of the `ConjunctiveGraph` object itself.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.
- [x] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [x] Updated relevant documentation to avoid inaccuracies.
  - [x] Considered adding additional documentation.
  - [x] Considered adding an example in `./examples` for new features.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Review by aucampia — APPROVED** [review]
@mielvds thanks for the PR. While I think it is pretty safe and uncontroversial it would still be good to have tests for this.

Also, we are trying to reduce the effort it takes to make a release, and one part of this is to keep the changelog up to date always:

https://github.com/RDFLib/rdflib/blob/cfa418074b27b12aac905ba266b002a237c5ff4c/CHANGELOG.md?plain=1#L201-L217

So it would be good if you could add tests and update the changelog, but I will try find some time this weekend to add tests and update the change on your PR branch if it is not done yet, as this is rather important to fix.

**Comment by aucampia** [comment]
@mielvds please share how you managed to trigger this if you can.

**Comment by mielvds** [comment]
Hi @aucampia 
I agree. I will add some tests and update the changelog. You can then check if they suffice. 

I triggered this while developing a documentation tool for shacl. I manage different shacl graphs as named graphs and got errors when printing the namespaces.

**Review by aucampia — APPROVED** [review]
Thank you very much for the test and changelog update @mielvds, the change looks good.

**Pull request merged**
