### PR TITLE
updated_graph.py

### PR DESCRIPTION
**Pull request by MuraliKrishna26**
fixes RDFLib/rdflib#903
Added code so that it can handle more than one predicate (taken in a tuple).

### CODE REVIEW

**Comment by nicholascar** [comment]
Hi @MuraliKrishna26, thanks for picking up this OWL2 issue. I *think* that your addition will do as expected, and it passes all tests, but please can you supply a test of your own demonstrating that your code now resolves that? You can perhaps use the example from Issue #903 that motivated this PR. It's RDFlib policy to have tests supplied for all PRs. Thanks!

**Comment by ashleysommer** [comment]
@MuraliKrishna26 I'm not super familiar with OWL2 patterns, but I believe the RDF identifiers in the supplied object tuple are supposed to be turned into a rdf List mechanism, then the list added as the object to the triple, rather than multiple triples added with different object.

**Comment by nicholascar** [comment]
The example Python from #903 is:

```python
g.add((URIRef(ns+"Answer"), RDF.type, RDFS.Datatype))
g.add((URIRef(ns+"Answer"), OWL.unionOf, (XSD.string, XSD.boolean, XSD.positiveInteger)))
g.add((URIRef(ns+"answer_value"), RDF.type, RDFS.Property))
g.add((URIRef(ns+"answer_value"), RDFS.domain, URIRef(ns+"Question")))
g.add((URIRef(ns+"answer_value"), RDFS.range, URIRef(ns+"Answer")))
```

This translates to RDF (Turtle) of:

```turtle
ns:Answer
    a rdfs:Dataype ;
    owl:unionOf (
        xsd:string
        xsd:boolean
        xsd:positiveInteger 
    ) ;
.

ns:answer_value
    a rdfs:Property ;
    rdfs:domain ns:Question ;
    rdfs:range ns:Answer ;
.
```

Yes, that syntax in the Turtle of `( xsd:string  xsd:boolean  xsd:positiveInteger )` represents "represents an `rdf:first`/`rdf:rest` list structure with the sequence of objects of the `rdf:first` statements being the order of the terms enclosed by `()`" as per the Turtle Spec [1] .

Here is `owl:unionOf` in Turtle from one of my projects describing the domain of a property:

```turtle
:vernacularName 
    a owl:DatatypeProperty ;
    rdfs:domain [ 
        a owl:Class ;
        owl:unionOf ( 
            :Host
            :SampleAnimal
        )
    ] ;
    rdfs:comment "The vernacular (common) name for the host or pest" ;
    skos:prefLabel "vernacular name" ;
.
```

So, back to my comment above: we need a test in this PR that shows this additional code doing the job it is claiming to do, not just a test for the error.

[1] https://www.w3.org/TR/turtle/#collections

**Comment by nicholascar** [comment]
@MuraliKrishna26, no tests supplied so I'll close this in a week if I don't hear back from you here.

**Comment by nicholascar** [comment]
Closing PR due to no response from @MuraliKrishna26

**Pull request closed without merging**
