### PR TITLE
Speedup ntriples parser

### PR DESCRIPTION
**Pull request by rchateauneu**
The performance test does:
g.parse("orkg.nt", format="nt")

Windows:
14.71s => 12.20 : 17% faster
Linux: 13.12 => 12.45: 5% faster.

Please note that about 15% of time is spent in codecs.readline, implying UTF-8 conversions due to opening the file in "rb" mode.

### CODE REVIEW

**Comment by rchateauneu** [comment]
I mistakenly added extra commits in this PR. Only 9b562bc and c1377a0 are relevant.

**Comment by white-gecko** [comment]
But 9b562bc and c1377a0 do not look very relevant

**Comment by rchateauneu** [comment]
Yes:

-  9b562bc is simply the merge.
- c1377a0 is the removal of an assert, but it does not harm.

**Comment by rchateauneu** [comment]
This change is halted for the moment because their might be interferences with:

- https://github.com/RDFLib/rdflib/pull/1222 Replace ByteIO with StringIO: This would eliminate utf-8 conversions, and also impact the whole processing chain from reading line from a file or a socket, to its regex parsing.
- https://github.com/RDFLib/rdflib/issues/1276 N-triples parser not in line with N-triples specification: It is probably better to ensure that ntriples parsing is functionally OK, before optimizing it.

However, some of optimizations it suggests, are now split into several small PRs, which are ready for merging, independently:
- https://github.com/RDFLib/rdflib/pull/1319
- https://github.com/RDFLib/rdflib/pull/1320
- https://github.com/RDFLib/rdflib/pull/1321
- https://github.com/RDFLib/rdflib/pull/1324

**Pull request closed without merging**
