### PR TITLE
Add support to parsing large xml inputs (https://github.com/RDFLib/rdflib/issues/749)

### PR DESCRIPTION
**Pull request by artreven**

### CODE REVIEW

**Comment by gromgull** [comment]
This fails with `huge_tree` is not a valid keyword argument on all python versions. 

We are quite lax with where we get elementtree from: https://github.com/RDFLib/rdflib/blob/master/rdflib/compat.py#L16-L36

I guess the default version doesn't support this?

**Comment by artreven** [comment]
I just checked what happens at my end: I use Python 3.5.2 and lxml 3.5.0. I get `etree` from `lxml` and the line `etree.XMLParser(huge_tree=True)` returns my the parser without any exceptions.
What could be the issue?

**Comment by niklasl** [comment]
As @gromgull says, the default etree from the standard library does not support this option:

```python
import xml.etree.ElementTree as etree

etree.XMLParser(huge_tree=True)
```

On Python 3, this fails with:

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
TypeError: 'huge_tree' is an invalid keyword argument for this function
```

Since lxml is an optional package for RDFLib, you cannot rely on it being available to support the non-standard keyword (`huge_tree`).

**Comment by artreven** [comment]
Sorry, I did not get the original comment from @gromgull at first, I thought `lxml` is the default version. I have added an `except` clause to provide a fallback in case of default version.

**Comment by gromgull** [comment]
Thanks! (and sorry about the delay)

**Pull request merged**
