### PR TITLE
Deprecate some more Graph API surface

### PR DESCRIPTION
**Pull request by ashleysommer**
Deprecate some more Graph API surface that will be removed in RDFLib 6.0.0

### CODE REVIEW

**Review by nicholascar — APPROVED** [review]

**Comment by ashleysommer** [comment]
Can't merge this yet. A lot of tests are failing.
Turns out some parts of rdflib (like a lot of tests) do `from rdflib.graph import RDFS`
With RDFS removed as an import here, those locations now fail.
I'll update this soon.

**Comment by nicholascar** [comment]
> Turns out some parts of rdflib (like a lot of tests) do from r`dflib.graph import RDFS` 

Yes, I've seen this and occasionally have done that myself, by mistake. It would be good to update everything so that `RDFS`, along with all namespaces are *always* imported from the same place, `rdflib.namespace`, not `rdflib.graph`. Good to finally address this small niggle

**Comment by ashleysommer** [comment]
Ok, turns out I was wrong. It wasn't used in the tests, but in the inline doctests in graph.py, I didn't know Travis tests those too.
I've updated those so should pass tests now.

**Comment by ashleysommer** [comment]
All tests pass, good to merge 👍

**Pull request merged**
