### PR TITLE
style: normalize quoting with black

### PR DESCRIPTION
**Pull request by aucampia**
# Summary of changes

This patch will result in black normalizing string quoting. This makes
for a more consistent codebase, this will mostly affect tests as this
setting was effectively enabled for some time on `rdflib/`.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
pre-commit.ci autofix

**Comment by aucampia** [comment]
Not sure why this was disabled but I think it makes things a bit easier if string quoting is normalized.

**Review by gjhiggins — APPROVED** [review]
Definitely worth it.

**Review by gjhiggins — APPROVED** [review]
confirmed

**Comment by aucampia** [comment]
pre-commit.ci autofix

**Comment by aucampia** [comment]
Merging this with only one approval as the only thing that made changes to runtime code here is black (via pre-commit.ci).

**Pull request merged**
