### PR TITLE
Fix handling of EXISTS inside BIND

### PR DESCRIPTION
**Pull request by aucampia**
# Summary of changes

This patch fixes an issue with `BIND( EXISTS ... )` in SPARQL,
for example:

```sparql
SELECT * WHERE {
    BIND(
        EXISTS {
            <http://example.com/a>
            <http://example.com/b>
            <http://example.com/c>
        }
        AS ?bound
    )
}
```

The graph pattern of `EXISTS` needs to be translated for it to operate
correctly during evaluation, but this was not happening. This patch
corrects that so that the graph pattern is translated as part of
translating `BIND`.

This patch also adds a bunch of tests for EXISTS to ensure there is no
regression and that various EXISTS cases function correctly.

Fixes https://github.com/RDFLib/rdflib/issues/1472

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Added tests for any changes that have a runtime impact.
- [x] Checked that all tests and type checking passes.
- For changes that have a potential impact on users of this project:
  - [x] Considered updating our changelog (`CHANGELOG.md`).
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Comment by aucampia** [comment]
@GreenfishK I think you know this stuff better than most, if you have time for a review it will be appreciated.

**Comment by aucampia** [comment]
@niklasl  @rchateauneu  you may also have some insights here.

**Comment by GreenfishK** [comment]
> @GreenfishK I think you know this stuff better than most, if you have time for a review it will be appreciated.

Hi @aucampia, I just saw your comment as I was not online over the weekend. Is the review still required?

**Comment by aucampia** [comment]
> > @GreenfishK I think you know this stuff better than most, if you have time for a review it will be appreciated.
> 
> Hi @aucampia, I just saw your comment as I was not online over the weekend. Is the review still required?

If you have time yes please, I'm fairly confident about this change but I'm not really as familiar with the SPARQL parsing, translation and evaluation as I think you are. Further if you can think of more corner cases to test, or just tests that would make you more comfortable with this change I would be happy to add them also.

**Review by gjhiggins — APPROVED** [review]
Did you intend to include the change to tox.ini? Not that I have any objection at all, just checking.

**Comment by aucampia** [comment]
> Did you intend to include the change to tox.ini? Not that I have any objection at all, just checking.

I did intend to include it, though it probably would have been better to not include it. It is mainly in the PR because the previous log format did not include the function name and it was a bit hard to read, and to fix this issue it helped a lot to see the function name that things were coming from.

Thanks for the reivews.

**Comment by aucampia** [comment]
Going to merge this on 2022-04-17 if there is no further feedback.

**Review by edmondchuc — APPROVED** [review]
Tests look good to me.

**Comment by aucampia** [comment]
Won't merge before #1838

**Pull request merged**
