### PR TITLE
Move Store API to work with identifiers, not graphs

### LINKED ISSUE #167: Clarify confusion around type of context element in ConjunctiveGraphs  and context aware stores
gromgull, 2011-08-20T07:58:07.000Z

In the ConjunctiveGraph, the context field is assumed to be a graph with the identifier set to the URI of the context, i.e. this is what happens if you create context like this: 

``` python
g=ConjunctiveGraph()
uri1=URIRef("http://example.org/mygraph1")
uri2=URIRef("http://example.org/mygraph2")

bob = URIRef(u'urn:bob')
likes = URIRef(u'urn:likes')
pizza = URIRef(u'urn:pizza')

g.get_context(uri1).add((bob, likes, pizza))
g.get_context(uri2).add((bob, likes, pizza))
```

Now g.contexts() returns a generator over some graphs. 

Now, for code working on the store level, i.e. serializers and parsers, there should perhaps not be any graph objects? 

I came across this when looking at the nquad parser, here: 

https://github.com/RDFLib/rdflib/blob/master/rdflib/plugins/parsers/nquads.py#L106

This adds context as simply an URI ref. 

I added a "work-around" to make the conjunctivegraph.contexts generator work "correctly" here: 

https://github.com/RDFLib/rdflib/blob/master/rdflib/graph.py#L1075

Is this ok?

### PR DESCRIPTION
**Pull request by oohlaf**
This is pull request #409 rebased against master to fix #167

### CODE REVIEW

**Comment by oohlaf** [comment]
I'll see if I can replicate the sparql tests locally, those did not run by the run_tests script on my machine

**Comment by oohlaf** [comment]
One build failure remains on python 3.4. Could use some help with that one.

**Comment by oohlaf** [comment]
Nah, this is weird. I finally managed to get Python3.4 to compile on my system to run the failing test case. And guess what, it does not fail. I can't replicate the build failure. Now what?

**Comment by nicholascar** [comment]
I'm very keen to see progress on this: it annoys me greatly not being able to identify graphs with a URI, as I think they should be. @ashleysommer any thoughts on the Python 3.4 oddity? I also don't get any errors running locally so perhaps we just need to rerun Travis?

**Comment by gromgull** [comment]
my 2c is get rid of py3.4 compatability - 3.6 and up only! :D

**Comment by nicholascar** [comment]
Closing and re-opening to re-trigger Travis

**Comment by nicholascar** [comment]
Hi @oohlaf, @ashleysommer and I have looked at this PR and we're going to discuss it further with others later tonight. We think a little more discussion is still needed so we're going to push this to a 5.0.0 release (a few months off) and not include it in a 4.3.0 release (shortly).

Well get back to you shortly (a few days) with our discussion.

**Comment by gjhiggins** [comment]
What's the status of the discussion? Amenable to a new PR?
I rebased this rebase as branch [identifier-as-context](https://github.com/gjhiggins/rdflib/tree/identifier-as-context) of my fork, all tests passing according to [GHActions]( https://github.com/gjhiggins/rdflib/actions/runs/1544170150)

**Comment by nicholascar** [comment]
I just discussed this with one of the co-maintainers on the phone today (@ashleysommer) and we are keen to make a proper move on this front. The recent PR that I put up for HexTuples was harder than it should have been due to this issue remaining unsolved.

I think we should be able to refer to contexts by URIRef, str of the URI or by context object (for backwards comparability). Also we should not have to set the publicID for ConjunctiveGraphs / Datasets manually when parsing multi graph data, e.g Trig, to get the default graph to work properly.

So I think we need a rather large set of changes here - or perhaps better worded and far reaching since the code changes may not be large - and they are possibly breaking unless reference by context object can still continue also. So this may be an RDFlib 7.0.0 thing.

I will put out a 6.1.0 shortly as this

**Comment by gjhiggins** [comment]
> I just discussed this with one of the co-maintainers on the phone today (@ashleysommer) and we are keen to make a proper move on this front.
Okay, now that the principle has been established, I'll reply substantively once I've organised my thoughts. Happy to shepherd this through.

**Comment by nicholascar** [comment]
Perhaps just type checking for a `Graph`, `URIRef` or `str` and then comparing that with `context`, `context.identifier` and `str(context.identifier)` is all that’s needed in graph.py and then a whole lot of work to ensure that it’s applied consistently in all other code? It backwards comparability is maintained with the context object option then I suppose the application across legacy code can proceed with no rush as it will keep working. Is there more to it than that? Iterating through `cg.contexts()` issues perhaps??

**Comment by gjhiggins** [comment]
Changes in the RDFLib codebase since gromgull's original PR unfortunately render this an incomplete  implementation.

**Pull request closed without merging**
